{
 "title": "Oracle Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "system", "label": "System", "query": { "query": "beacon_slot" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(chain_head_block{},instance)"
    }
   },
   { "name": "job", "label": "job", "query": "geth" }
  ]
 },
 "panels": [
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Oracle: Distance From Finalized Slot",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "oracle_distance_from_finalized_slot",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Oracle: Latest Processed Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracle_latest_processed_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Oracle: Known Root and Slot",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "targets": [
    { "expr": "oracle_known_root_and_slot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_block{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle: Latest Processed Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracle_latest_processed_slot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Teku - Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(beacon_peer_count{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Teku - Current Epoch",
   "type": "stat",
   "description": "The current epoch according to system time",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(beacon_epoch{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Teku - Slots Behind",
   "type": "stat",
   "description": "Number of slots the head block is behind.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(beacon_slot{instance=~\"$system\"} - beacon_head_slot{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Current slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(beacon_slot{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Geth - Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"geth\"}"
    }
   ]
  },
  {
   "title": "Geth - Finalized block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(chain_head_finalized)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Geth - Latest Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(chain_head_header{instance=~\"$instance\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Geth + Teku Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$system\"}",
     "legendFormat": "Teku memory usage"
    },
    {
     "expr": "system_memory_held{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "Geth memory usage"
    },
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$system\"}) + sum(system_memory_held{instance=~\"$instance\", job=~\"$job\"})",
     "legendFormat": "Total Memory Usage"
    }
   ]
  },
  {
   "title": "Geth + Teku CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])",
     "legendFormat": "teku CPU usage"
    },
    {
     "expr": "system_cpu_sysload{instance=~\"$instance\", job=~\"$job\"} / 100",
     "legendFormat": "geth CPU usage"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])) + sum(system_cpu_sysload{instance=~\"$instance\", job=~\"$job\"} / 100)",
     "legendFormat": "Total CPU usage"
    }
   ]
  },
  {
   "title": "Teku Client stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$system\"}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} {{job}}"
      }
     ]
    },
    {
     "title": "Teku - Peers over time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "beacon_peer_count{instance=~\"$system\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Participation Rate",
     "type": "graph",
     "description": "Overall participation rate in the chain. The Correct Validators must be above 2/3rd for the chain to finalize.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max(beacon_previous_live_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"})",
       "legendFormat": "Live Validators"
      },
      {
       "expr": "max(beacon_previous_correct_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"})",
       "legendFormat": "Correct Validators"
      },
      {
       "expr": "max(beacon_previous_live_sync_committee{instance=~\"$system\"} / (512 * 32))",
       "legendFormat": "Sync Committee Participation"
      }
     ]
    }
   ]
  },
  {
   "title": "Geth Client Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(system_memory_allocs{instance=~\"$instance\", job=~\"$job\"}[1m])",
       "legendFormat": "alloc"
      },
      {
       "expr": "system_memory_used{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "used"
      },
      {
       "expr": "system_memory_held{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "held"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "system_cpu_sysload{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "system"
      },
      {
       "expr": "system_cpu_syswait{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "iowait"
      },
      {
       "expr": "system_cpu_procload{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "geth"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "p2p_peers{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "peers"
      },
      {
       "expr": "rate(p2p_dials{instance=~\"$instance\", job=~\"$job\"}[1m])",
       "legendFormat": "dials"
      },
      {
       "expr": "rate(p2p_serves{instance=~\"$instance\", job=~\"$job\"}[1m])",
       "legendFormat": "serves"
      }
     ]
    },
    {
     "title": "Storage size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "eth_db_chaindata_disk_size{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "leveldb"
      },
      {
       "expr": "eth_db_chaindata_ancient_size{instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "ancient"
      }
     ]
    }
   ]
  }
 ]
}